// Package provider is the toy example provider: it composes the tfkit provider
// base with the tfgen-generated resource registration (resources_gen.go) and
// the generated widget resource (widget_resource.go + widget_resource_gen.go).
//
// This file is hand-written — it is the small, stable seam a scaffolded
// provider owns. Everything else in this package is generated by tfgen from
// testdata/toy.openapi.yaml and committed so the example builds as-is.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/provider"

	"github.com/infobloxopen/devedge-terraform-sdk/tfkit"
)

// New returns the toy provider factory for providerserver.Serve. It builds on
// the reusable tfkit base — endpoint/token configuration and the shared client
// — and registers the generated resources. A real provider swaps the type name
// and, in a private overlay, a provider-specific auth binding.
func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return tfkit.NewProvider(tfkit.ProviderConfig{
			TypeName:  "toy",
			Version:   version,
			Resources: Resources(),
		})
	}
}
