// Code generated by tfgen. DO NOT EDIT.

// Provider module: github.com/infobloxopen/devedge-terraform-sdk/examples/terraform-provider-toy
package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

// Resources returns the resource constructors this provider serves. The
// provider (see provider.go) passes them to tfkit.NewProvider.
func Resources() []func() resource.Resource {
	return []func() resource.Resource{
		NewWidgetResource,
	}
}
