// Code generated by tfgen. DO NOT EDIT.

package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/infobloxopen/devedge-terraform-sdk/tfkit"
)

var (
	_ resource.Resource                = (*widgetResource)(nil)
	_ resource.ResourceWithConfigure   = (*widgetResource)(nil)
	_ resource.ResourceWithImportState = (*widgetResource)(nil)
)

// widgetCollectionPath is the Widget collection URL path.
const widgetCollectionPath = "/v1/widgets"

// NewWidgetResource constructs the toy.example.com/Widget resource.
func NewWidgetResource() resource.Resource { return &widgetResource{} }

type widgetResource struct {
	client *tfkit.Client
}

func (r *widgetResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_widget"
}

func (r *widgetResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = WidgetResourceSchema(ctx)
}

func (r *widgetResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = tfkit.ResourceClient(req, resp)
}

// createBody projects the model onto a JSON create request. OUTPUT_ONLY fields
// are excluded — the service sets them.
func (m WidgetModel) createBody() map[string]any {
	body := map[string]any{}
	tfkit.SetString(body, "accountId", m.AccountId)
	tfkit.SetString(body, "category", m.Category)
	tfkit.SetString(body, "color", m.Color)
	tfkit.SetString(body, "displayName", m.DisplayName)
	tfkit.SetString(body, "etag", m.Etag)
	tfkit.SetString(body, "id", m.Id)
	tfkit.SetString(body, "parentId", m.ParentId)
	tfkit.SetString(body, "secretToken", m.SecretToken)
	tfkit.SetString(body, "sku", m.Sku)
	tfkit.SetInt64(body, "weight", m.Weight)
	return body
}

// updateBody projects the model onto a JSON update request (IMMUTABLE and
// OUTPUT_ONLY fields excluded) and returns the AIP-134 field mask.
func (m WidgetModel) updateBody() (map[string]any, []string) {
	body := map[string]any{}
	tfkit.SetString(body, "category", m.Category)
	tfkit.SetString(body, "displayName", m.DisplayName)
	tfkit.SetString(body, "etag", m.Etag)
	tfkit.SetString(body, "parentId", m.ParentId)
	tfkit.SetString(body, "secretToken", m.SecretToken)
	tfkit.SetString(body, "sku", m.Sku)
	tfkit.SetInt64(body, "weight", m.Weight)
	return body, tfkit.MaskKeys(body)
}

// apply copies a decoded API object onto the model. INPUT_ONLY fields are not
// echoed by the service, so they keep the value the plan/state already holds.
func (m *WidgetModel) apply(data map[string]any) {
	m.AccountId = tfkit.GetString(data, "accountId")
	m.ArchivedTime = tfkit.GetString(data, "archivedTime")
	m.Category = tfkit.GetString(data, "category")
	m.Color = tfkit.GetString(data, "color")
	m.DeleteTime = tfkit.GetString(data, "deleteTime")
	m.DisplayName = tfkit.GetString(data, "displayName")
	m.Etag = tfkit.GetString(data, "etag")
	m.Id = tfkit.GetString(data, "id")
	m.Name = tfkit.GetString(data, "name")
	m.ParentId = tfkit.GetString(data, "parentId")
	m.Sku = tfkit.GetString(data, "sku")
	m.Weight = tfkit.GetInt64(data, "weight")
}

func (r *widgetResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan WidgetModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out map[string]any
	if err := r.client.DoCreate(ctx, widgetCollectionPath, plan.createBody(), &out); err != nil {
		resp.Diagnostics.AddError("Unable to create toy.example.com/Widget", err.Error())
		return
	}
	plan.apply(out)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *widgetResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state WidgetModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out map[string]any
	if err := r.client.DoRead(ctx, widgetCollectionPath+"/"+url.PathEscape(state.Id.ValueString()), &out); err != nil {
		resp.Diagnostics.AddError("Unable to read toy.example.com/Widget", err.Error())
		return
	}
	state.apply(out)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *widgetResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan WidgetModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body, mask := plan.updateBody()
	q := url.Values{}
	if len(mask) > 0 {
		q.Set("updateMask", strings.Join(mask, ","))
	}
	var out map[string]any
	if err := r.client.DoUpdate(ctx, widgetCollectionPath+"/"+url.PathEscape(plan.Id.ValueString()), q, body, &out); err != nil {
		resp.Diagnostics.AddError("Unable to update toy.example.com/Widget", err.Error())
		return
	}
	plan.apply(out)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *widgetResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state WidgetModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DoDelete(ctx, widgetCollectionPath+"/"+url.PathEscape(state.Id.ValueString())); err != nil {
		resp.Diagnostics.AddError("Unable to delete toy.example.com/Widget", err.Error())
		return
	}
}

func (r *widgetResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tfkit.ImportStatePassthroughID(ctx, "id", req, resp)
}
