// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func WidgetResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "account_id is the tenant key: set by the server from the auth context and",
				MarkdownDescription: "account_id is the tenant key: set by the server from the auth context and",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"archived_time": schema.StringAttribute{
				Computed:            true,
				Description:         "AIP-136: set by ArchiveWidget; non-nil means the widget is archived.",
				MarkdownDescription: "AIP-136: set by ArchiveWidget; non-nil means the widget is archived.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"category": schema.StringAttribute{
				Optional:            true,
				Description:         "category is a string-backed enum (allowed_values → OpenAPI enum, AC-4).",
				MarkdownDescription: "category is a string-backed enum (allowed_values → OpenAPI enum, AC-4).",
				Validators: []validator.String{
					stringvalidator.OneOf("standard", "premium"),
				},
			},
			"color": schema.StringAttribute{
				Optional:            true,
				Description:         "color is IMMUTABLE (explicit field_behavior): set at create, never updated.",
				MarkdownDescription: "color is IMMUTABLE (explicit field_behavior): set at create, never updated.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"delete_time": schema.StringAttribute{
				Computed:            true,
				Description:         "AIP-148: soft-delete timestamp; set by Delete, cleared by Undelete.",
				MarkdownDescription: "AIP-148: soft-delete timestamp; set by Delete, cleared by Undelete.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Required:            true,
				Description:         "display_name is client-REQUIRED (explicit field_behavior).",
				MarkdownDescription: "display_name is client-REQUIRED (explicit field_behavior).",
			},
			"etag": schema.StringAttribute{
				Optional: true,
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "id is USER_SETTABLE (AIP-133): the annotation alone derives IMMUTABLE for the",
				MarkdownDescription: "id is USER_SETTABLE (AIP-133): the annotation alone derives IMMUTABLE for the",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "name is the AIP-122 resource name, e.g. \"widgets/abc123\".",
				MarkdownDescription: "name is the AIP-122 resource name, e.g. \"widgets/abc123\".",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"parent_id": schema.StringAttribute{
				Optional:            true,
				Description:         "parent_id is a cross-service reference to another Widget (AIP-124). Widget is",
				MarkdownDescription: "parent_id is a cross-service reference to another Widget (AIP-124). Widget is",
			},
			"secret_token": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "secret_token is write-only material (secret → INPUT_ONLY): accepted on write,",
				MarkdownDescription: "secret_token is write-only material (secret → INPUT_ONLY): accepted on write,",
			},
			"sku": schema.StringAttribute{
				Optional:            true,
				Description:         "sku is storage NOT NULL but NOT client-required — proving not_null is never",
				MarkdownDescription: "sku is storage NOT NULL but NOT client-required — proving not_null is never",
			},
			"weight": schema.Int64Attribute{
				Optional: true,
			},
		},
	}
}

type WidgetModel struct {
	AccountId    types.String `tfsdk:"account_id"`
	ArchivedTime types.String `tfsdk:"archived_time"`
	Category     types.String `tfsdk:"category"`
	Color        types.String `tfsdk:"color"`
	DeleteTime   types.String `tfsdk:"delete_time"`
	DisplayName  types.String `tfsdk:"display_name"`
	Etag         types.String `tfsdk:"etag"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	ParentId     types.String `tfsdk:"parent_id"`
	SecretToken  types.String `tfsdk:"secret_token"`
	Sku          types.String `tfsdk:"sku"`
	Weight       types.Int64  `tfsdk:"weight"`
}
