// Command terraform-provider-toy is a runnable terraform-plugin-framework
// provider generated from testdata/toy.openapi.yaml. It is the Terraform mirror
// of the devedge-cli-sdk examples/ib shell: a small hand-written entry point
// (provider.go) composing tfkit with a committed generated resource module.
//
// The provider serves the widget resource generated by tfgen; a
// `terraform apply` against it would manage toy.example.com/Widget resources
// over the service's REST API through the tfkit runtime.
package main

import (
	"context"
	"flag"
	"log"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"

	"github.com/infobloxopen/devedge-terraform-sdk/examples/terraform-provider-toy/internal/provider"
)

// version is overridden at release time via -ldflags.
var version = "dev"

func main() {
	var debug bool
	flag.BoolVar(&debug, "debug", false, "run with support for debuggers like delve")
	flag.Parse()

	err := providerserver.Serve(context.Background(), provider.New(version), providerserver.ServeOpts{
		Address: "registry.terraform.io/infobloxopen/toy",
		Debug:   debug,
	})
	if err != nil {
		log.Fatal(err.Error())
	}
}
